#!/bin/bash
# dns_update.sh - Allows user to set up to 3 DNS servers or use the router's default.

# Ensure script is run as root
if [ "$(id -u)" -ne 0 ]; then
dialog --title "Permission Denied" --msgbox "This script must be run as root. Please use sudo or run as root." 7 50
exit 1
fi

# Get current DNS servers
CURRENT_DNS=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}')

# Display current DNS settings
dialog --title "Current DNS Settings" --msgbox "Current DNS Servers:\n$CURRENT_DNS\n\nYou can specify up to 3 DNS servers.\nIf you leave any blank, your router's default DNS will be used." 12 60

# Ask how many DNS servers the user wants to specify
dialog --title "DNS Configuration" --menu "How many DNS servers would you like to specify?" 20 50 3 \
1 "Specify 1 DNS server" \
2 "Specify 2 DNS servers" \
3 "Specify 3 DNS servers" 2> /tmp/dns_count

DNS_COUNT=$(cat /tmp/dns_count)
rm -f /tmp/dns_count

if [[ -z "$DNS_COUNT" ]]; then
dialog --title "No Changes" --msgbox "DNS settings remain unchanged." 7 50
exit 0
fi

# Prompt user for DNS servers based on their choice
DNS_SERVERS=()
for (( i=1; i<=DNS_COUNT; i++ )); do
dialog --title "DNS Configuration" --inputbox \
"Enter DNS server $i IP address (leave blank to use the router's default):" 8 50 2> /tmp/dns_entry
DNS_ENTRY=$(cat /tmp/dns_entry)
rm -f /tmp/dns_entry

if [[ -n "$DNS_ENTRY" ]]; then
DNS_SERVERS+=("$DNS_ENTRY")
fi
done

# Construct new resolv.conf content
echo "# Generated by dns_update.sh" > /etc/resolv.conf
if [[ ${#DNS_SERVERS[@]} -eq 0 ]]; then
echo "# No custom DNS servers set. Using router's default." >> /etc/resolv.conf
else
for dns in "${DNS_SERVERS[@]}" do
echo "nameserver $dns" >> /etc/resolv.conf
done
fi

dialog --title "DNS Updated" --msgbox "DNS settings have been updated successfully!\n\nIf any entries were left blank, your router's default DNS will be used.\n\nTo make changes persistent, update Netplan or NetworkManager settings." 12 60

# Ask if user wants to restart networking
dialog --title "Restart Network" --yesno "Would you like to restart networking to apply changes immediately?" 8 50
if [ $? -eq 0 ]; then
systemctl restart networking
dialog --title "Network Restarted" --msgbox "Network services have been restarted to apply new DNS settings." 7 50
else
dialog --title "Reminder" --msgbox "Changes will take effect on the next reboot or network restart." 7 50
fi

clear
exit 0
